### PR TITLE
Feature/iso-4217 implement missing methods

### PR DESCRIPTION
**Pull request by DmitriyBobrovskiy**
Hey,
I've added method for returning all found currencies by code:
* `GetCurrenciesByCode`

And related unit tests.

### CODE REVIEW

**Comment by maisak** [comment]
Hey! Thanks for your contribution. But I have some concerns. By returning a full currency object, you introduce a misleading behavior to the library. For example, let's take code 978:

image

Considering your code, we will get a currency related to Aland Islands, but it is obviously not what user expects! As we already have methods to resolve code by number and vice versa, and there is a method to get a collection of all currencies by code/number - I don't really see the need for suggested methods, quite the opposite, I consider them harmful (as they create confusion).

**Comment by DmitriyBobrovskiy** [comment]
But the problem is that there are no methods for getting currency by code.
I agree that what I suggested is not correct behavior, what would you say if I change my code to return all currencies by code?

**Comment by maisak** [comment]
That's a good idea! Would be great if you can do that.

**Comment by DmitriyBobrovskiy** [comment]
Done, can you review it again, please?

**Comment by maisak** [comment]
Thanks for your contribution!

**Comment by DmitriyBobrovskiy** [comment]
Thank you too, can you please update nuget package?

**Pull request merged**
